emperor(turza,simulation).
emperor(sadhin,html).
emperor(udoy,sleep).
emperor(rajesh,love).
emperor(minhaj,superman).
emperor(turza,css).
emperor(tanu,deeplearning).
emperor(bipro,css).
emperor(munna,html).
emperor(tanvir,poet).
emperor(arif,math).
emperor(sadhin,css).
likes(ismill,dating).
likes(rajesh,dating).
likes(minhaj,photograph).
